version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "monday"
          time: "06:00"
          timezone: "UTC"
      open-pull-requests-limit: 5
      commit-message:
          prefix: "ci"
    - package-ecosystem: "cargo"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "monday"
          time: "06:00"
          timezone: "UTC"
      open-pull-requests-limit: 5
      commit-message:
          prefix: "deps"
      groups:
          rust-minor-and-patch:
              update-types:
                  - "minor"
                  - "patch"
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "monday"
          time: "06:00"
          timezone: "UTC"
      open-pull-requests-limit: 5
      commit-message:
          prefix: "deps"
      groups:
          js-minor-and-patch:
              update-types:
                  - "minor"
                  - "patch"
