export default {
    extends: ["@commitlint/config-conventional"],
    rules: {
        "type-enum": [2, "always", ["feat", "fix", "docs", "style", "refactor", "perf", "test", "build", "ci", "chore", "revert", "wip"]],
        "type-case": [2, "always", "lower-case"],
        "type-empty": [2, "never"],
        "subject-empty": [2, "never"],
        "subject-case": [2, "always", "lower-case"],
        "subject-full-stop": [2, "never", "."],
        "header-max-length": [2, "always", 100],
        "body-max-line-length": [0, "always", 200],
        "scope-enum": [
            1,
            "always",
            [
                "api-gateway",
                "customer-api",
                "admin-api",
                "schedule-api",
                "customer-web",
                "admin-web",
                "customer-mobile",
                "agent",
                "agent-config",
                "session-store",
                "central-client",
                "fas-server",
                "heartbeat",
                "ndsctl",
                "auth",
                "database",
                "cache",
                "config",
                "email",
                "export",
                "http",
                "logging",
                "metrics",
                "observability",
                "queue",
                "sms",
                "storage",
                "types",
                "utilities",
                "webhooks",
                "deps",
                "ci",
                "docs",
                "release",
            ],
        ],
    },
    helpUrl: "https://github.com/conventional-changelog/commitlint/#what-is-commitlint",
};
