[package]
name = "ru5ty-gate-admin-api"
description = "Admin API"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "admin_api"
path = "src/lib.rs"

[[bin]]
name = "admin-api"
path = "src/main.rs"

[dependencies]
async-trait = "0.1.92"
axum = { version = "0.8.9", features = ["macros"] }
base64 = "0.23.1"
chrono = "0.4.45"
dotenvy = "0.15.7"
futures-util = "0.3.34"
hex = "0.4.3"
ru5ty-gate-auth = { version = "1.0.0", path = "../../../common/auth" }
ru5ty-gate-cache = { version = "1.0.0", path = "../../../common/cache" }
ru5ty-gate-config = { version = "1.0.0", path = "../../../common/config" }
ru5ty-gate-database = { version = "1.0.0", path = "../../../common/database" }
ru5ty-gate-email = { version = "1.0.0", path = "../../../common/email" }
ru5ty-gate-export = { version = "1.0.0", path = "../../../common/export" }
ru5ty-gate-http = { version = "1.0.0", path = "../../../common/http" }
ru5ty-gate-logging = { version = "1.0.0", path = "../../../common/logging" }
ru5ty-gate-observability = { version = "1.0.0", path = "../../../common/observability" }
ru5ty-gate-types = { version = "1.0.0", path = "../../../common/types" }
ru5ty-gate-utilities = { version = "1.0.0", path = "../../../common/utilities" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.11.0"
sqlx = { version = "0.9.0", default-features = false, features = ["postgres", "uuid", "chrono", "json", "derive"] }
subtle = "2.6.1"
thiserror.workspace = true
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "signal", "net", "time", "sync"] }
totp-rs = { version = "6.0.0", features = ["qr", "otpauth", "gen_secret"] }
tower = { version = "0.5.3", features = ["util"] }
tower-http = { version = "0.7.1", features = ["cors"] }
tracing = "0.1.44"
uuid = { version = "1.26.1", features = ["v4", "serde"] }
validator = { version = "0.21.0", features = ["derive"] }


[lints]
workspace = true

[dev-dependencies]
async-trait = "0.1.92"
ru5ty-gate-central-client = { version = "1.0.0", path = "../../../common/central-client" }
secrecy = "0.10.3"
http-body-util = "0.1.5"
tower = { version = "0.5.3", features = ["util"] }
